remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-responsive-image
title: Project Graveyard
description: Welcome to the numerous projects I have worked on since 2021
collections:
  projects:
    output: true
responsive_image:
  template: _layouts/default.html
  sizes:
    - width: 320
    - width: 480
    - width: 800
