remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll_picture_tag 
title: Project Graveyard
description: Welcome to the numerous projects I have worked on since 2021
collections:
  projects:
    output: true
