plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Project Graveyard
description: Welcome to the numerous projects I have worked on since 2021
blog: Musings of the Project Graveyard
exclude:
  - theme-creator
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - tailwind.config.js
  - tailwind.css
collections:
  courses:
    output: true
  projects:
    output: true
  posts:
    output: true
  recipes:
    output: true
  dojos:
    output: true
